### PR TITLE
remove left over gateways

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17)

### CODE REVIEW

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[lib/cleaner/gatewayCleaner.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZRiN8u1mDROc2VWCIo:-MZRiN8u1mDROc2VWCIp:b-lamlnk) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/42162dfdab4195d4521ff3c95136db8f7651c7f7/lib/cleaner/gatewayCleaner.js#L11)):*
> ```
> let algorithms = await storeManager.getAlgorithms();
> ```

don't get all...
storeManager.getAlgorithms({kind: nodeKind.Gateway}); 
___
*[lib/store/store-manager.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZRiTpr-oLgCoru-C2g:-MZRiTpr-oLgCoru-C2h:b-ia52i5) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/42162dfdab4195d4521ff3c95136db8f7651c7f7/lib/store/store-manager.js#L11)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         log.info(
>             `initialized mongo with options: ${JSON.stringify(this._db.config)}`,
>             { component }
>         );
> ```
</details>

remove the prettier
___
*[lib/store/store-manager.js, line 34 at r1](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZRiX7ICi_o0Bu0FXfz:-MZRiX7ICi_o0Bu0FXg-:b20th0e) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/42162dfdab4195d4521ff3c95136db8f7651c7f7/lib/store/store-manager.js#L34)):*
> ```
>  hasResult: false,
> ```
??? 
___
*[tests/test.js, line 37 at r1](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZRipE0CHFYrNJ5hhSj:-MZRipE0CHFYrNJ5hhSk:bvsuev9) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/42162dfdab4195d4521ff3c95136db8f7651c7f7/tests/test.js#L37)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     nock("http://localhost:3000")
>       .persist()
>       .post("/internal/v1/exec/stop")
>       .reply(200);
> ```
</details>

no need

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[lib/cleaner/gatewayCleaner.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZRiN8u1mDROc2VWCIo:-MZSPabx3rJcjTYlxoy9:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/42162dfdab4195d4521ff3c95136db8f7651c7f7/lib/cleaner/gatewayCleaner.js#L11)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> let algorithms = await storeManager.getAlgorithms();
> ```

don't get all...
storeManager.getAlgorithms({kind: nodeKind.Gateway}); 
</blockquote></details>

Done.
___
*[lib/store/store-manager.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZRiTpr-oLgCoru-C2g:-MZfxi2r-kjCnXl10O_r:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/42162dfdab4195d4521ff3c95136db8f7651c7f7/lib/store/store-manager.js#L11)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>         log.info(
>             `initialized mongo with options: ${JSON.stringify(this._db.config)}`,
>             { component }
>         );
> ```
remove the prettier
</blockquote></details>

Done.
___
*[lib/store/store-manager.js, line 34 at r1](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZRiX7ICi_o0Bu0FXfz:-MZfxiZ0AFQJhLf0yi4z:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/42162dfdab4195d4521ff3c95136db8f7651c7f7/lib/store/store-manager.js#L34)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  hasResult: false,
> ```
??? 
</blockquote></details>

Done.
___
*[tests/test.js, line 37 at r1](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZRipE0CHFYrNJ5hhSj:-MZfxl0j-UQO_E1s104M:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/42162dfdab4195d4521ff3c95136db8f7651c7f7/tests/test.js#L37)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     nock("http://localhost:3000")
>       .persist()
>       .post("/internal/v1/exec/stop")
>       .reply(200);
> ```
no need
</blockquote></details>

Done.

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[tests/test.js, line 39 at r2](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZg-aqg60-s6d5apFd2:-MZg-aqg60-s6d5apFd3:b1rk39v) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/b8384c2c23d41bde97ada8e619e0032aefee0a3e/tests/test.js#L39)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>   beforeEach(async () => {
>     await storeManager.init(main);
>     await storeManager._db.jobs.createMany(
>       executions.map((e, i) => ({ jobId: `job-${i}`, pipeline: e }))
>     );
>     await storeManager._db.algorithms.deleteMany({}, { allowNotFound: true });
>     await storeManager._db.algorithms.createMany(algorithms);
>   });
> ```
</details>



this code is duplicate with the upper beforeEach
___
*[tests/mocks/algorithms.js, line 20 at r2](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZg-kBW0-RUF1WN6OKK:-MZg-kBW0-RUF1WN6OKL:b-lx35ik) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/b8384c2c23d41bde97ada8e619e0032aefee0a3e/tests/mocks/algorithms.js#L20)):*
> ```
> ····
> ```

Tab space

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @NassiHarel)

___
*[tests/test.js, line 37 at r1](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZRipE0CHFYrNJ5hhSj:-MZgPuyU8YaQqYg6Upw2:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/42162dfdab4195d4521ff3c95136db8f7651c7f7/tests/test.js#L37)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[tests/test.js, line 39 at r2](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZg-aqg60-s6d5apFd2:-MZgPvUpEG_OkUaUmkO6:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/b8384c2c23d41bde97ada8e619e0032aefee0a3e/tests/test.js#L39)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>   beforeEach(async () => {
>     await storeManager.init(main);
>     await storeManager._db.jobs.createMany(
>       executions.map((e, i) => ({ jobId: `job-${i}`, pipeline: e }))
>     );
>     await storeManager._db.algorithms.deleteMany({}, { allowNotFound: true });
>     await storeManager._db.algorithms.createMany(algorithms);
>   });
> ```


this code is duplicate with the upper beforeEach
</blockquote></details>

Done.
___
*[tests/mocks/algorithms.js, line 20 at r2](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZg-kBW0-RUF1WN6OKK:-MZgPxEpEuLhSvmtziTj:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/b8384c2c23d41bde97ada8e619e0032aefee0a3e/tests/mocks/algorithms.js#L20)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> ····
> ```

Tab space
</blockquote></details>

Done.

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[lib/cleaner/gatewayCleaner.js, line 8 at r3](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZg_GJZ0iBjNnFn66bN:-MZg_GJ_6JIKRjiQ-gU-:b-dm5st1) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/5e9bd96ee2635c214d676de7ebdb31657886bebc/lib/cleaner/gatewayCleaner.js#L8)):*
> ```
> const jobs = await storeManager.getPipelines();
> ```
Maybe we should get `jobs` only if we have gateways

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/cleaner/gatewayCleaner.js, line 8 at r3](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-MZg_GJZ0iBjNnFn66bN:-MZlQ2h0-YHdNxIemTfl:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-cleaner/blob/5e9bd96ee2635c214d676de7ebdb31657886bebc/lib/cleaner/gatewayCleaner.js#L8)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const jobs = await storeManager.getPipelines();
> ```
Maybe we should get `jobs` only if we have gateways
</blockquote></details>

Done.

**Review by nassiharel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/pipeline-cleaner/17#-:-MZlQl830bC9vesSQJA_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
